import { create } from "@storybook/theming/create";

export default create({
  base: "light",
  fontBase: "Inter, sans-serif",
  fontCode: "monospace",
  base: "light",
  brandTitle: "Prismane",
  brandUrl: "https://www.prismane.io",
  brandImage: "https://i.ibb.co/W05W195/logo-text.png",
  brandTarget: "_blank",
  colorPrimary: "#0f172a",
  colorSecondary: "#ec4899",
  appBg: "#ffffff",
  appContentBg: "#ffffff",
  appBorderColor: "#ec4899",
  appBorderRadius: 4,
  textColor: "#0f172a",
  textInverseColor: "#ffffff",
  barTextColor: "#9E9E9E",
  barSelectedColor: "#ec4899",
  barBg: "#ffffff",
  inputBg: "#ffffff",
  inputBorder: "#0f172a",
  inputTextColor: "#0f172a",
  inputBorderRadius: 2,
});
